### PR TITLE
Fix warning in package.json: change bugs[web] to bugs[url]

### PR DESCRIPTION
**Pull request by jmalonzo**

### CODE REVIEW

**Comment by fb55** [comment]
The fourth fix for that issue… This project doesn't seem to be continued, so it won't get merged. (But you may use [my fork](https://github.com/fb55/node-htmlparser), that is still actively developed and has that bug fixed by default.)

**Comment by jmalonzo** [comment]
The author just updated the license last month. It would be nice if your fork is the one that gets picked up by npm. Have you tried talking/emailing the author and perhaps just take ownership/maintainership of the project?

**Comment by fb55** [comment]
I've added my fork as "htmlparser2" to npm. Project relying on htmlparser just need to change their requires to htmlparser2 and they are ready to go. 

Taking ownership of this project may not be the best idea. I removed browser support as I don't need it (they already have an HTML parser, don't they?) and introduced some breaking changes (eg. a new internal structure for handlers, no more verbose output), so any project using those features may be broken.

**Comment by jmalonzo** [comment]
Thanks. Fair enough. I'll keep that in mind if I see a project that uses htmlparser.

Cheers.

**Pull request closed without merging**
