### PR TITLE
Fix: npm WARN htmlparser@1.7.3 package.json: bugs['web'] should probably be bugs['url']

### PR DESCRIPTION
**Pull request by TooTallNate**
Fix: npm WARN htmlparser@1.7.3 package.json: bugs['web'] should probably be bugs['url']

### CODE REVIEW

**Comment by matthewmueller** [comment]
+1

**Comment by feross** [comment]
+1

**Comment by wridgers** [comment]
+1

**Comment by luakri** [comment]
+1

**Comment by TooTallNate** [comment]
@tautologistics ping ^

**Comment by DanielePalombo** [comment]
+1

**Comment by tautologistics** [comment]
Sorry everyone, personal stuff got in the way for a while. Catching up on everything now...

**Pull request merged**
