### PR TITLE
Check for empty tags should be case-insensitive

### PR DESCRIPTION
**Pull request by fgnass**
With this patch, jsdom passes the W3C DOM test-suite which uses upper-case tags.

### CODE REVIEW

**Comment by tmpvar** [comment]
@Chris, can you take a peek at these patches?  I'd like to cut another release of jsdom, but this has become a blocker

Thanks!
-- Elijah

**Comment by tautologistics** [comment]
Sorry for the delay. Been really busy pushing node usage at a big .com.

Looking through them now...

**Comment by tautologistics** [comment]
OK, so to expedite this I have included the changes as is in a v1.7.0 but changed the "includeLocation" to be part of a passed in options parameter to the Parser constructor. I do not like the idea of backdoor, implicit object properties.

The getLocation() method appears to add about 10% to the parsing time but I believe that could be cut in half by using indexOf() or a cached regex instead of inspecting every character in the stream for a "\r" or "\n". I do not have time to do this right now so additional patches are welcome (as are some test cases for this getLocation()) =)

**Comment by tmpvar** [comment]
thank you!

**Comment by tautologistics** [comment]
Problem! I could not let the feature go without even a basic test case so I created one. Turns out that element position calculation completely falls apart with chunked parsing.

I have to disable this feature until a working version can be made. I do not have the time to attempt a fix right now but perhaps you or fgnass can look into it? If you can provide me with a fix I will get a v1.7.2 out ASAP.

Here's the test: https://gist.github.com/704977

**Comment by fgnass** [comment]
With this fix the test passes in chunked-mode, but I'd consider it quite an ugly hack. If you're unhappy with it, we could also move it into a feature-branch for now and just cherry-pick 67dc4c286685152f783fbcaf192646f8a197ff76 which fixes our blocker.

**Comment by tautologistics** [comment]
I have merged locally and am reviewing now.

BTW - Solutions are sometimes ugly but that should not always hold things up. We can look at refining this later if necessary.

**Comment by tautologistics** [comment]
OK, everything is stitched up as 1.7.2 and pushed to npm as well.

**Comment by tmpvar** [comment]
thanks a ton!

**Pull request merged**
