### PR TITLE
Restructured, cleaned code; improved speed

### PR DESCRIPTION
**Pull request by fb55**
The code was a mess. I spent some time restructuring it, so that it could be understood easily. I dropped support for browsers, they already have HTML parsers.

### CODE REVIEW

**Comment by fb55** [comment]
To clarify: I don't expect this to be merged, there are probably too many changes. But anyone who's interested may use my code.

**Comment by matthewmueller** [comment]
This is awesome - I'm getting 2x speed on this patch with no modifications to my existing code other than changing the requires to "htmlparser2"

Also the directory structure definitely needed a facelift. Thanks!

Is there any way you can open up issues on your forked page, or does everything go back to tautologistics repo?

**Comment by fb55** [comment]
The issues tab is opened now. Thank you for the feedback :D

**Comment by deanmao** [comment]
hmm, it's too bad this won't run on the browser -- that's the only reason I use htmlparser

browsers may already have html parsers, but there are other reasons why this package is used there.

**Comment by matthewmueller** [comment]
@deanmao I'm curious, what's your use case? The only instance I can think of is running server-side tests in the browser instead the command line.

Also, this has become a hilarious pull request:

```
+ 3,536 additions 
- 3,273 deletions
```

...maybe tautologistics will merge it ;-)

**Comment by deanmao** [comment]
There's lots of use cases for in browser...  for example, you're manipulating html in the browser, but you'd like to do it the same way as on the server side so that the same set of js can be in both places.

For me, I have a pseudo html that doesn't really map to proper html tags.  The browser is too smart for it's own good and would convert unknown tags to something that suits itself.  For example, if I created the &lt;x&gt; tag, it might convert it into a &lt;div&gt; for me if I start appending children to it.

**Comment by deanmao** [comment]
Also, why bother making it a pull request?  Why not just make this one a different npm module that was derived from htmlparser?  I'm sure others would still find it useful even though it no longer resembles the original node-htmlparser.

You could just attribute the original npm module in package.json and give it a separate name.  I'm sure there will be users who will appreciate this module for what it is.

EDIT: I see that it is already under htmlparser2...  makes sense.  I also see that it can be run in the browser as well, it doesn't make use of node specific apis.

**Comment by matthewmueller** [comment]
I'd use JSDOM for something like that... it's slow but it's a closer representation to the original DOM.

As far as the pull request, check the original pull request date - it was 7 months ago. You can install this version with `npm install htmlparser2`. @FB55 has done a great job improving this library. I'm using his fork in my library, cheerio (http://github.com/MatthewMueller/cheerio).

**Comment by deanmao** [comment]
JSDOM doesn't actually include a parser if you've read their source.  JSDOM actually just uses htmlparser 1.x behind the scenes, so it's not really that much gain over from using htmlparser directly.  You'll probably notice it fails on the same sets of bad html.

**Comment by matthewmueller** [comment]
Ohhh thats right.. so you're looking for something that exactly matches the browser's parser? (ie. `<x> => <div>`)

**Comment by deanmao** [comment]
well, not really...  i'm specifically looking for something that doesn't match the browser's parser at all :-)

**Pull request closed without merging**
