### PR TITLE
Include 'sunos' to enable installation on SmartOS, Illumos, etc.

### PR DESCRIPTION
**Pull request by notmatt**
Or, since it's pure JS, removing the 'os' line seems like a good option.

In any case, all tests pass on SmartOS, and no problems in use.

```
# node runtests.js 
The "sys" module is now called "util". It should have a similar interface.
[RSS (2.0)]: passed
[Atom (1.0)]: passed
[Unquoted attributes]: passed
[Enforce empty tags]: passed
[XML Namespace]: passed
[Extra spaces in tag]: passed
[Ignore empty tags]: passed
[Single Tag 1]: passed
[Single Tag 2]: passed
[Only text]: passed
[Unescaped chars in script]: passed
[Comment within text within script]: passed
[Script source in comment]: passed
[Comment within text]: passed
[Postion data]: passed
[Singular attribute]: passed
[Text outside tags]: passed
[Options 'ignoreWhitespace' set to 'true']: passed
[Option 'verbose' set to 'false']: passed
[Basic test]: passed
[Unescaped chars in style]: passed
[Special char in comment]: passed
Total tests: 22
Failed tests: 0
```

### CODE REVIEW

**Comment by notmatt** [comment]
Actually a bit of a conflict between npm behaviour and the spec here; the latter claims that 'solaris' is the valid os name for Solar-ish OSes, but npm likes sunos (which is the reported name for SmartOS).

**Comment by tautologistics** [comment]
Thank you but I am just going to remove the "os" entry (1.7.6 coming shortly)

**Comment by notmatt** [comment]
Sounds good to me, thanks!

**Comment by tautologistics** [comment]
BTW - 1.7.6 is up on npm now. Just wrapping up work on 2.0 as well.

**Pull request closed without merging**
